[package]
name = "rebar"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
walkdir = "2.3.1"
num_cpus = "1.13.0"
threadpool = "1.8.1"
